// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversidadeDeContoso.Dados;

namespace UniversidadeDeContoso.Migrations
{
    [DbContext(typeof(UniversidadeContext))]
    partial class UniversidadeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UniversidadeDeContoso.Models.Curso", b =>
                {
                    b.Property<int>("CursoID");

                    b.Property<int>("Creditos");

                    b.Property<string>("Nome");

                    b.HasKey("CursoID");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("UniversidadeDeContoso.Models.Estudante", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataDeMatricula");

                    b.Property<string>("Nome");

                    b.Property<string>("SobreNome");

                    b.HasKey("ID");

                    b.ToTable("Estudante");
                });

            modelBuilder.Entity("UniversidadeDeContoso.Models.Materia", b =>
                {
                    b.Property<int>("MateriaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CursoID");

                    b.Property<int>("EstudanteID");

                    b.Property<int?>("Nota");

                    b.HasKey("MateriaID");

                    b.HasIndex("CursoID");

                    b.HasIndex("EstudanteID");

                    b.ToTable("Materia");
                });

            modelBuilder.Entity("UniversidadeDeContoso.Models.Materia", b =>
                {
                    b.HasOne("UniversidadeDeContoso.Models.Curso", "Curso")
                        .WithMany("Materias")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("UniversidadeDeContoso.Models.Estudante", "Estudante")
                        .WithMany("Materias")
                        .HasForeignKey("EstudanteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
